# user nginx; # Docker の User 指定で実行するため、この指定は不要です
daemon off;
worker_processes auto;
error_log /dev/stderr info;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       @nginx@/conf/mime.types;
    default_type  application/octet-stream;
    access_log    /dev/stdout;

    server {
        listen       80;
        server_name  localhost;

        location / {
            root   @docs@/share/nginx/html;
            index  index.html index.htm;
        }

        # Temp paths for non-privileged user
        client_body_temp_path /tmp/nginx_client_body;
        proxy_temp_path /tmp/nginx_proxy;
        fastcgi_temp_path /tmp/nginx_fastcgi;
        uwsgi_temp_path /tmp/nginx_uwsgi;
        scgi_temp_path /tmp/nginx_scgi;
    }
}
