[book]
authors = ["tatsukichi"]
language = "ja"
src = "src"
title = "mdbook Example Document"

[build]
build-dir = "book"

[output.html]
additional-css = []
git-repository-url = ""

[output.html.playground]
editable = false
